### ISSUE TITLE
Module Store and Packs Store unreachable when using a proxy server

### ISSUE THREAD

**Issue by RogueSnipa** [saltcorn/saltcorn#1601]
**Describe the bug**
I assume that the Saltcorn application cannot receive modules when using internet access via a proxy server.
This is probably because the [node-fetch](https://www.npmjs.com/package/node-fetch) module cannot use a proxy.

**To Reproduce**
1. Launch a new container on a server that has internet access only through a proxy server. When creating a container, you must specify the environment variables "HTTP_PROXY" and "HTTPS_PROXY".
2. All application pages are available except http://ServerUrl:3000/plugins

**Additional context**
docker compose file used to create the container:
```yaml
version: "3.7"

services:
  saltcorn-app:
    image: saltcorn/saltcorn:0.8.2
    container_name: saltcorn
    command: "serve"
    restart: always
    ports:
      - 3000:3000
    environment:
      - SALTCORN_SESSION_SECRET=saltcornsalt
      - PGHOST=192.168.100.10
      - PGUSER=saltcornadmin
      - PGDATABASE=saltcorndb
      - PGPASSWORD=adminpassword
      - HTTP_PROXY=http://192.168.100.20:3128
      - HTTPS_PROXY=http://192.168.100.20:3128
```
timeout errors are registered in the container log when accessing the http://ServerUrl:3000/plugins.
```log
FetchError: request to https://store.saltcorn.com/api/extensions failed, reason: connect ETIMEDOUT 172.67.221.60:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
fetch store error FetchError: request to https://store.saltcorn.com/api/packs?fields=name,description failed, reason: connect ETIMEDOUT 104.21.17.44:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
fetch store error FetchError: request to https://store.saltcorn.com/api/packs?fields=name,description failed, reason: connect ETIMEDOUT 104.21.17.44:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
```

#1587
