### ISSUE TITLE
Q: How to select table data (in list or view) with OR operator

### ISSUE THREAD

**Issue by pyhedgehog** [saltcorn/saltcorn#1860]
Let's pretend we have two tables implementing graph (i.e. for [mermaid plugin](https://github.com/AleksandrSokolov/saltcorn-view-mermaid)):
```yaml
nodes:
  id: PK
  name: String

links:
  id: PK
  src: Key to nodes
  tgt: Key to nodes
```
How to select all connections of some node?
In SQL I mean: `select * from links l join nodes s on l.src=s.id join nodes t on l.tgt=t.id where :param in (l.src,l.tgt)`.
I can pass `?tgt=123` or `?src=123`, but not `?src|tgt=123`.
